"""Table pipeline for the CL x hallucination pilot.

Usage:  python analysis/make_tables.py --results results/ --out tables/

Emits:
  results_main.tex  booktabs LaTeX table -- rows = checkpoints (S0..S4, J1..J4),
                    cols = CHAIR_s, CHAIR_i, POPE-adv F1, POPE yes-rate, mean task acc.
                    Missing values are printed as "--", never fabricated. A mean over
                    fewer than the 4 tasks is marked with a dagger.
  results_full.csv  machine-readable long format: one row per checkpoint x metric.
                    Audit columns parse_fail_rate and truncation_rate are ALWAYS
                    present; they are left empty ("") where genuinely not measured
                    (empty = NO-DATA, not zero).

Python 3.9 compatible; stdlib only.
"""
import argparse
import csv
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from results_io import (CKPTS, TASKS, TASK_METRIC, POPE_SPLITS, load_results,
                        chair_metric, pope_metric, pope_truncation,
                        task_field, task_score)

ARM = {"S0": "base", "S1": "seq", "S2": "seq", "S3": "seq", "S4": "seq",
       "J1": "joint", "J2": "joint", "J3": "joint", "J4": "joint"}
STAGE = {"S0": 0, "S1": 1, "S2": 2, "S3": 3, "S4": 4,
         "J1": 1, "J2": 2, "J3": 3, "J4": 4}


def fmt(v, nd=3):
    return "--" if v is None else ("%.*f" % (nd, v))


def mean_task_acc(table, ckpt):
    """(mean over available task scores, n_tasks_present). Never imputes."""
    vals = [task_score(table, ckpt, t) for t in TASKS]
    present = [v for v in vals if v is not None]
    if not present:
        return None, 0
    return sum(present) / len(present), len(present)


# ------------------------------------------------------------- results_main.tex

def write_main_tex(table, path):
    lines = []
    lines.append("% Auto-generated by analysis/make_tables.py -- do not edit by hand.")
    lines.append("% Missing values are '--' (checkpoint/metric not evaluated yet).")
    lines.append("% $^{\\dagger}$ = mean over fewer than 4 tasks (only available scores;")
    lines.append("%   nothing imputed). POPE yes-rate is over all three splits pooled.")
    lines.append("% flickr contributes caption unigram-F1 (trajectory signal), not accuracy.")
    lines.append("\\begin{tabular}{lrrrrr}")
    lines.append("\\toprule")
    lines.append("Checkpoint & CHAIR$_s$ & CHAIR$_i$ & POPE-adv F1 & "
                 "POPE yes-rate & Mean task acc \\\\")
    lines.append("\\midrule")

    def row_for(c):
        m, n_present = mean_task_acc(table, c)
        if m is None:
            mean_cell = "--"
        elif n_present == len(TASKS):
            mean_cell = "%.3f" % m
        else:
            mean_cell = "%.3f$^{\\dagger}$" % m
        cells = [c,
                 fmt(chair_metric(table, c, "chair_s")),
                 fmt(chair_metric(table, c, "chair_i")),
                 fmt(pope_metric(table, c, "adversarial", "f1")),
                 fmt(pope_metric(table, c, "all", "yes_rate")),
                 mean_cell]
        return " & ".join(cells) + " \\\\"

    for c in ("S0", "S1", "S2", "S3", "S4"):
        lines.append(row_for(c))
    lines.append("\\midrule")
    for c in ("J1", "J2", "J3", "J4"):
        lines.append(row_for(c))
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("[make_tables] wrote %s" % path)


# ------------------------------------------------------------- results_full.csv

CSV_FIELDS = ["ckpt", "arm", "stage", "source", "metric", "value", "n",
              "parse_fail_rate", "truncation_rate"]


def csv_rows_for_ckpt(table, c):
    """Long-format rows for one checkpoint. Only measured values -- no imputation."""
    rows = []

    def add(source, metric, value, n=None, pfr=None, trunc=None):
        if value is None:
            return
        rows.append({
            "ckpt": c, "arm": ARM[c], "stage": STAGE[c], "source": source,
            "metric": metric, "value": value,
            "n": "" if n is None else n,
            "parse_fail_rate": "" if pfr is None else pfr,
            "truncation_rate": "" if trunc is None else trunc,
        })

    # CHAIR summary (chair.json). CHAIR has no answer-parsing step -> pfr empty.
    ch_n = chair_metric(table, c, "n_captions")
    ch_tr = chair_metric(table, c, "truncation_rate")
    for key in ("chair_s", "chair_i", "mentions_per_caption", "mean_new_tokens",
                "truncation_rate"):
        add("chair", "chair_%s" % key if not key.startswith("chair_") else key,
            chair_metric(table, c, key), n=ch_n, pfr=None, trunc=ch_tr)

    # POPE per split + pooled (pope.json); truncation audit derived from
    # pope_gen.jsonl when present (results_io), otherwise left empty.
    for split in POPE_SPLITS + ["all"]:
        sp_n = pope_metric(table, c, split, "n")
        sp_pfr = pope_metric(table, c, split, "parse_fail_rate")
        sp_tr = pope_truncation(table, c, split)
        for key in ("f1", "accuracy", "precision", "recall", "yes_rate"):
            add("pope", "pope_%s_%s" % (split, key),
                pope_metric(table, c, split, key), n=sp_n, pfr=sp_pfr, trunc=sp_tr)

    # Tasks (task_<t>.json)
    for t in TASKS:
        t_n = task_field(table, c, t, "n")
        t_pfr = task_field(table, c, t, "parse_fail_rate")
        t_tr = task_field(table, c, t, "truncation_rate")
        add("task", "task_%s_%s" % (t, TASK_METRIC[t]), task_score(table, c, t),
            n=t_n, pfr=t_pfr, trunc=t_tr)
        add("task", "task_%s_mean_new_tokens" % t,
            task_field(table, c, t, "mean_new_tokens"), n=t_n, pfr=t_pfr, trunc=t_tr)

    # Mean task accuracy (n = number of tasks averaged, NOT example count)
    m, n_present = mean_task_acc(table, c)
    if m is not None:
        add("derived", "mean_task_acc", round(m, 4), n=n_present)

    return rows


def write_full_csv(table, path):
    all_rows = []
    for c in CKPTS:
        if table.get(c) is None:
            continue  # absent checkpoint -> no rows, never fabricated
        all_rows.extend(csv_rows_for_ckpt(table, c))
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        w.writeheader()
        w.writerows(all_rows)
    print("[make_tables] wrote %s (%d metric rows)" % (path, len(all_rows)))


# ------------------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", required=True, help="results dir with S0..S4,J1..J4")
    ap.add_argument("--out", required=True, help="output dir for tables")
    args = ap.parse_args()

    table = load_results(args.results)
    os.makedirs(args.out, exist_ok=True)
    write_main_tex(table, os.path.join(args.out, "results_main.tex"))
    write_full_csv(table, os.path.join(args.out, "results_full.csv"))
    print("[make_tables] DONE")


if __name__ == "__main__":
    main()
